import * as T from "@effect-ts/core/Effect"
import { pipe } from "@effect-ts/core/Function"
import * as O from "@effect-ts/core/Option"
import type { NextPage } from 'next'
import Head from 'next/head'
import * as React from "react"
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [maybeMessage, setMessage] = React.useState<O.Option<string>>(O.none)
  React.useEffect(() => {
    const cancel = pipe(
      T.succeed("something that shouldn't exist"),
      T.chain((message) => T.succeedWith(() => setMessage(O.some(message)))),
      T.runCancel
    )
    return () => {
      T.runFiber(cancel)
    }
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>Original App</title>
        <meta name="description" content="Generated by create next app to be tested with effect!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to {O.getOrElse_(maybeMessage, () => "...")}
        </h1>
      </main>
    </div>
  )
}

export default Home
